#!/usr/bin/env bash
# Generates data/resource_added.yaml — maps each resource content file to the
# date it was first added to the repo (first commit that created it), derived
# from git history. Used by the "Recently Added" section on /resources/.
#
# Must be run with full git history available (not a shallow clone) — the
# GitHub Actions deploy workflow runs this before `hugo build`.
#
# Usage: tools/generate-resource-dates.sh

set -euo pipefail

cd "$(dirname "$0")/.."

OUT="data/resource_added.yaml"
mkdir -p data

echo "# Generated by tools/generate-resource-dates.sh — do not edit by hand." > "$OUT"
echo "# Maps each resource content path to the date it was first added (git history)." >> "$OUT"

find content/resources -mindepth 2 -name "*.md" ! -name "_index.md" ! -path "*/press/*" ! -name "contribute.md" | sort | while read -r f; do
  added=$(git log --diff-filter=A --follow --format=%ad --date=short -- "$f" | tail -1)
  if [ -z "$added" ]; then
    # Fallback: file not yet committed (e.g. new in working tree) — use today.
    added=$(date -u +%Y-%m-%d)
  fi
  # YAML key: forward-slash path relative to content/, quoted.
  key=${f#content/}
  echo "\"$key\": \"$added\"" >> "$OUT"
done

echo "Wrote $OUT"
